{
  "provinces": [
    { "name": "黑龙江", "zones": [{ "name": "寒温带", "key": "cold_temperate", "adjustment_factor": 1.25, "description": "年均温-4~4°C，无霜期90-120天" }, { "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.15, "description": "年均温1~4°C，无霜期120-150天" }] },
    { "name": "吉林", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.15, "description": "年均温3~6°C，无霜期120-150天" }] },
    { "name": "辽宁", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.1, "description": "年均温7~10°C，无霜期140-170天" }, { "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温9~11°C，无霜期160-200天" }] },
    { "name": "内蒙古", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.2, "description": "年均温0~6°C，无霜期100-140天" }, { "name": "干旱温带", "key": "arid_temperate", "adjustment_factor": 1.15, "description": "年均温4~8°C，无霜期130-160天" }] },
    { "name": "北京", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温11~13°C，无霜期180-200天" }] },
    { "name": "天津", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温12~14°C，无霜期190-210天" }] },
    { "name": "河北", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温10~14°C，无霜期170-210天" }] },
    { "name": "山西", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.05, "description": "年均温8~13°C，无霜期150-190天" }] },
    { "name": "山东", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温11~14°C，无霜期180-220天" }] },
    { "name": "河南", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "年均温13~15°C，无霜期190-220天" }, { "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.92, "description": "年均温15~16°C，无霜期220-240天" }] },
    { "name": "陕西", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.05, "description": "年均温9~14°C，无霜期160-210天" }, { "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.92, "description": "年均温14~16°C，无霜期220-250天" }] },
    { "name": "甘肃", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.2, "description": "年均温5~10°C，无霜期120-170天" }, { "name": "干旱温带", "key": "arid_temperate", "adjustment_factor": 1.18, "description": "年均温6~9°C，无霜期130-160天" }] },
    { "name": "宁夏", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.15, "description": "年均温6~9°C，无霜期130-160天" }] },
    { "name": "青海", "zones": [{ "name": "高原温带", "key": "plateau_temperate", "adjustment_factor": 1.3, "description": "年均温-2~8°C，无霜期60-120天" }] },
    { "name": "新疆", "zones": [{ "name": "中温带", "key": "mid_temperate", "adjustment_factor": 1.15, "description": "北疆：年均温4~8°C，无霜期140-170天" }, { "name": "干旱温带", "key": "arid_temperate", "adjustment_factor": 1.05, "description": "南疆：年均温10~13°C，无霜期180-210天" }] },
    { "name": "西藏", "zones": [{ "name": "高原温带", "key": "plateau_temperate", "adjustment_factor": 1.35, "description": "年均温-3~8°C，无霜期50-110天" }] },
    { "name": "四川", "zones": [{ "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.92, "description": "盆地：年均温16~18°C，无霜期280-320天" }, { "name": "高原温带", "key": "plateau_temperate", "adjustment_factor": 1.2, "description": "川西高原：年均温2~8°C，无霜期80-140天" }] },
    { "name": "重庆", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.88, "description": "年均温17~18°C，无霜期300天以上" }] },
    { "name": "湖北", "zones": [{ "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.9, "description": "年均温15~17°C，无霜期230-260天" }] },
    { "name": "湖南", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.88, "description": "年均温16~18°C，无霜期270-300天" }] },
    { "name": "江西", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.88, "description": "年均温17~19°C，无霜期260-300天" }] },
    { "name": "安徽", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "淮北：年均温14~15°C，无霜期200-220天" }, { "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.9, "description": "江淮：年均温15~16°C，无霜期220-250天" }] },
    { "name": "江苏", "zones": [{ "name": "暖温带", "key": "warm_temperate", "adjustment_factor": 1.0, "description": "淮北：年均温13~14°C，无霜期200-210天" }, { "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.9, "description": "苏南：年均温15~16°C，无霜期230-250天" }] },
    { "name": "浙江", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.85, "description": "年均温16~18°C，无霜期250-280天" }] },
    { "name": "上海", "zones": [{ "name": "北亚热带", "key": "north_subtropical", "adjustment_factor": 0.9, "description": "年均温15~16°C，无霜期230-250天" }] },
    { "name": "福建", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.85, "description": "闽北：年均温17~19°C，无霜期260-300天" }, { "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.82, "description": "闽南：年均温20~22°C，基本无霜" }] },
    { "name": "广东", "zones": [{ "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.82, "description": "年均温20~23°C，基本无霜" }] },
    { "name": "广西", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.85, "description": "桂北：年均温17~19°C，无霜期280-320天" }, { "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.82, "description": "桂南：年均温21~23°C，基本无霜" }] },
    { "name": "海南", "zones": [{ "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.8, "description": "热带季风气候，年均温23~26°C，全年无霜" }] },
    { "name": "云南", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.88, "description": "滇中：年均温15~18°C，无霜期250-300天" }, { "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.82, "description": "滇南：年均温20~23°C，基本无霜" }, { "name": "高原温带", "key": "plateau_temperate", "adjustment_factor": 1.2, "description": "滇西北高原：年均温5~12°C，无霜期150-200天" }] },
    { "name": "贵州", "zones": [{ "name": "中亚热带", "key": "mid_subtropical", "adjustment_factor": 0.9, "description": "年均温14~16°C，无霜期260-290天" }] },
    { "name": "台湾", "zones": [{ "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.8, "description": "热带-亚热带，年均温22~25°C，全年无霜" }] },
    { "name": "香港", "zones": [{ "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.8, "description": "亚热带季风气候，年均温23°C，全年无霜" }] },
    { "name": "澳门", "zones": [{ "name": "南亚热带", "key": "south_subtropical", "adjustment_factor": 0.8, "description": "亚热带季风气候，年均温22°C，全年无霜" }] }
  ]
}
